### ISSUE TITLE
Add new GitHub Actions workflow to submit dependency tree samples on changes to main branch

### ISSUE THREAD

**Issue by rmgrimm** [FwMotion/3scale-cms#41]
The new workflow should use the [maven-dependency-tree-action](https://github.com/marketplace/actions/maven-dependency-tree-dependency-submission) to submit samples to GitHub Insights. The new workflow should only run on changes to pom files made in the `main` branch

**Comment by Monoradioactivo** [comment]
Hi there! I've submitted a PR addressing this issue. I'd appreciate any feedback you might have! https://github.com/FwMotion/3scale-cms/pull/66

**Comment by rmgrimm** [comment]
Resolved by #66
