### ISSUE TITLE
Add GitHub Actions workflow to run tests on pull requests

### ISSUE THREAD

**Issue by rmgrimm** [FwMotion/3scale-cms#64]

**Comment by ayushsarode** [comment]
I'm interested in tackling this issue. Could you assign it to me? Additionally, I have some familiarity with workflows. Could you provide more details on what needs to be done?

**Comment by rmgrimm** [comment]
@ayushsarode Thanks for the interest. We do not need a greeting.yaml; instead, the workflow should run `./mvnw clean verify` on pull requests to ensure that the build completes and tests pass successfully with the requested changes.

**Comment by ayushsarode** [comment]
Can I name the file ```build.yaml```?
